# Generated by Django 4.1.6 on 2023-02-13 14:36

from django.db import migrations, models
import django.db.models.deletion
import main_page.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('location_address', models.TextField(max_length=300)),
                ('country', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField(blank=True, max_length=1000)),
                ('bed_quantity', models.PositiveSmallIntegerField(blank=True)),
                ('baths_quantity', models.PositiveSmallIntegerField(blank=True)),
                ('is_visible', models.BooleanField(help_text='Is property offer is visible on site.')),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.Realtor.get_file_name)),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=25)),
                ('short_about', models.CharField(help_text='Short description, less than 120 chars.', max_length=120)),
                ('instagram_link', models.CharField(blank=True, max_length=500)),
                ('twitter_link', models.CharField(blank=True, max_length=500)),
                ('facebook_link', models.CharField(blank=True, max_length=500)),
                ('linkedin_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('property_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.realtor'),
        ),
    ]
