# Generated by Django 4.1.6 on 2023-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_property_realtor_propertyphoto_property_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='font_image_of_offer_page',
            field=models.BooleanField(default=False),
        ),
    ]
