# Generated by Django 4.1.6 on 2023-02-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_propertyphoto_font_image_of_offer_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='recommended_offer',
            field=models.BooleanField(default=False, help_text='This offer will be displayed in Popular Properties on Main page andin Featured Properties on Properties page.'),
        ),
    ]
