# Generated by Django 4.1.6 on 2023-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_property_recommended_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0, help_text='Price in US dollar.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='recommended_offer',
            field=models.BooleanField(default=False, help_text='This offer will be displayed in Popular Properties on Main page and in Featured Properties on Properties page.'),
        ),
    ]
