# Generated by Django 4.1.6 on 2023-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_property_price_alter_property_recommended_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(default=0, help_text='Price in US dollar.', max_length=15),
        ),
    ]
