# Generated by Django 4.1.6 on 2023-02-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_ourbenefits_alter_property_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourbenefits',
            name='agents_point',
        ),
        migrations.RemoveField(
            model_name='ourbenefits',
            name='house_point',
        ),
        migrations.RemoveField(
            model_name='ourbenefits',
            name='safety_point',
        ),
        migrations.AddField(
            model_name='ourbenefits',
            name='agents_point_header',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourbenefits',
            name='agents_point_heading_text',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourbenefits',
            name='house_point_header',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourbenefits',
            name='house_point_heading_text',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourbenefits',
            name='safety_point_header',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourbenefits',
            name='safety_point_heading_text',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
