# Generated by Django 4.1.6 on 2023-02-14 13:01

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_customersays_alter_propertyphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='visible_in_our_agents',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customersays',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.CustomerSays.get_file_name),
        ),
    ]
