# Generated by Django 4.1.6 on 2023-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_realtor_visible_in_our_agents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourbenefits',
            name='block_1_heading_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ourbenefits',
            name='block_2_heading_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ourbenefits',
            name='block_3_heading_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ourbenefits',
            name='block_4_heading_text',
            field=models.CharField(max_length=100),
        ),
    ]
