# Generated by Django 4.1.6 on 2023-02-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_alter_ourbenefits_block_1_heading_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersays',
            options={'verbose_name': '5. Customer says', 'verbose_name_plural': '5. Customer says'},
        ),
        migrations.AlterModelOptions(
            name='herobackgroundphotos',
            options={'verbose_name': '2. Hero background photos', 'verbose_name_plural': '2. Hero background photos'},
        ),
        migrations.AlterModelOptions(
            name='heroheader',
            options={'verbose_name': '1. Hero header', 'verbose_name_plural': '1. Hero header'},
        ),
        migrations.AlterModelOptions(
            name='ourbenefits',
            options={'verbose_name': '4. Our benefits', 'verbose_name_plural': '4. Our benefits'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('is_visible', 'recommended_offer', 'realtor', 'price', 'country'), 'verbose_name': '3. Property', 'verbose_name_plural': '3. Property'},
        ),
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': '6. Our agents', 'verbose_name_plural': '6. Our agents'},
        ),
    ]
