# Generated by Django 4.1.6 on 2023-02-15 06:57

import about_us.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsTopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_heading_text', tinymce.models.HTMLField(max_length=800)),
                ('right_heading_text', tinymce.models.HTMLField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='FirstBenefitsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_point_header', models.TextField(max_length=500)),
                ('house_point_heading_text', models.TextField(max_length=500)),
                ('agents_point_header', models.TextField(max_length=500)),
                ('agents_point_heading_text', models.TextField(max_length=500)),
                ('safety_point_header', models.TextField(max_length=500)),
                ('safety_point_heading_text', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to=about_us.models.FirstBenefitsBlock.get_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='PhotosAndNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to=about_us.models.PhotosAndNumbers.get_file_name)),
                ('image_2', models.ImageField(upload_to=about_us.models.PhotosAndNumbers.get_file_name)),
                ('image_3', models.ImageField(upload_to=about_us.models.PhotosAndNumbers.get_file_name)),
                ('block_1_header_number', models.CharField(max_length=10)),
                ('block_1_heading_text', models.CharField(max_length=100)),
                ('block_2_header_number', models.CharField(max_length=10)),
                ('block_2_heading_text', models.CharField(max_length=100)),
                ('block_3_header_number', models.CharField(max_length=10)),
                ('block_3_heading_text', models.CharField(max_length=100)),
                ('block_4_header_number', models.CharField(max_length=10)),
                ('block_4_heading_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecondBenefitsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_point_header', models.TextField(max_length=500)),
                ('house_point_heading_text', models.TextField(max_length=500)),
                ('agents_point_header', models.TextField(max_length=500)),
                ('agents_point_heading_text', models.TextField(max_length=500)),
                ('safety_point_header', models.TextField(max_length=500)),
                ('safety_point_heading_text', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to=about_us.models.SecondBenefitsBlock.get_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=about_us.models.TeamMember.get_file_name)),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=25)),
                ('short_about', models.CharField(help_text='Short description, less than 120 chars.', max_length=120)),
                ('instagram_link', models.CharField(blank=True, max_length=500)),
                ('twitter_link', models.CharField(blank=True, max_length=500)),
                ('facebook_link', models.CharField(blank=True, max_length=500)),
                ('linkedin_link', models.CharField(blank=True, max_length=500)),
                ('visible_in_our_agents', models.BooleanField(default=True)),
            ],
        ),
    ]
