# Generated by Django 4.1.6 on 2023-02-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_aboutustopinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutustopinfo',
            options={'verbose_name': '1. Top info block', 'verbose_name_plural': '1. Top info blocks'},
        ),
        migrations.AlterModelOptions(
            name='firstbenefitsblock',
            options={'verbose_name': '2. First benefits block', 'verbose_name_plural': '2. First benefit blocks'},
        ),
        migrations.AlterModelOptions(
            name='photosandnumbers',
            options={'verbose_name': '4. Photos and numbers block', 'verbose_name_plural': '4. Photos and numbers blocks'},
        ),
        migrations.AlterModelOptions(
            name='secondbenefitsblock',
            options={'verbose_name': '3. Second benefits block', 'verbose_name_plural': '3. Second benefits blocks'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': '5. Team member', 'verbose_name_plural': '5. Team members'},
        ),
    ]
