# Generated by Django 4.1.7 on 2023-02-17 10:42

from django.db import migrations, models
import services.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesInfoOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('small_description', models.TextField(max_length=500)),
                ('heading_text_left', tinymce.models.HTMLField(max_length=1000)),
                ('heading_text_right', tinymce.models.HTMLField(max_length=1000)),
                ('little_logo', models.PositiveSmallIntegerField(default=1, help_text='1 - House with tablet "NEW"\n, 2 - Regular house, 3 - Building, 4 - Agent in front of the house, 5 - House in the hand, 6 - Modern house.')),
                ('photo_1', models.ImageField(upload_to=services.models.ServicesInfoOffer.get_file_name)),
                ('photo_2', models.ImageField(upload_to=services.models.ServicesInfoOffer.get_file_name)),
                ('photo_3', models.ImageField(upload_to=services.models.ServicesInfoOffer.get_file_name)),
                ('font_image_for_service_page', models.ImageField(help_text='Image will show on the background of the service offer', upload_to=services.models.ServicesInfoOffer.get_file_name)),
                ('is_visible', models.BooleanField(default=True, help_text='Is service visible on site.')),
            ],
            options={
                'verbose_name': 'Services Info',
                'verbose_name_plural': 'Services Info',
            },
        ),
    ]
