# Generated by Django 4.1.7 on 2023-02-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesinfooffer',
            options={'verbose_name': '1. Services Info', 'verbose_name_plural': '1. Services Info'},
        ),
    ]
