# Generated by Django 4.1.6 on 2023-02-16 09:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', tinymce.models.HTMLField(max_length=200)),
                ('open_hours', tinymce.models.HTMLField(max_length=200)),
                ('email', tinymce.models.HTMLField(max_length=200)),
                ('call', tinymce.models.HTMLField(max_length=200)),
            ],
            options={
                'verbose_name': 'Contact info block',
                'verbose_name_plural': 'Contact info block',
            },
        ),
    ]
