# Generated by Django 4.1.7 on 2023-02-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_contactinfoleft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfoleft',
            options={'verbose_name': '2. Contact info block', 'verbose_name_plural': '2. Contact info block'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-date_of_the_request',), 'verbose_name': '1. Contact Requests', 'verbose_name_plural': '1. Contact Requests'},
        ),
    ]
