# Generated by Django 4.1.7 on 2023-02-18 17:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_contactinfoleft_phone_for_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', tinymce.models.HTMLField(max_length=200)),
                ('source_url', models.URLField()),
            ],
            options={
                'verbose_name': '3. Sources',
                'verbose_name_plural': '3. Sources',
            },
        ),
    ]
