# Generated by Django 4.1.7 on 2023-02-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0005_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfoleft',
            name='phone_for_footer',
            field=models.IntegerField(),
        ),
    ]
