# Generated by Django 4.1.7 on 2023-02-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0006_alter_contactinfoleft_phone_for_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('pinterest', models.URLField(blank=True)),
                ('dribbble', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': '4. Media links',
                'verbose_name_plural': '4. Media links',
            },
        ),
    ]
