# Generated by Django 4.1.7 on 2023-02-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimagesforpages',
            options={'verbose_name': 'Background images for pages', 'verbose_name_plural': 'Background images for pages'},
        ),
    ]
