# Generated by Django 4.1.7 on 2023-02-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_backgroundimagesforpages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimagesforpages',
            options={'verbose_name': '1. Background images for pages', 'verbose_name_plural': '1. Background images for pages'},
        ),
    ]
